### ISSUE TITLE
Create Rudimentary Main View Page

### ISSUE THREAD

**Issue by djpace14** [smileydts/death-or-glory#9]
Display your player name at bottom. 

Display other players at the table - static icons or layout.

**Comment by smileydts** [comment]
[This ](https://www.w3schools.com/)is the site I start with whenever I have my first encounter with any new language or popular tool.  It has really basic tutorials that help you get your feet wet.  They have HTML, CSS, JS, AJAX, etc.

**Comment by smileydts** [comment]
https://xkcd.com/844/

**Comment by djpace14** [comment]
Need to figure out how to make the layout and display adaptive to different screen sizes.

**Comment by djpace14** [comment]
I just did a commit and sync with a new index.html on the branch - feature/dog-8-player-id-page

**Comment by djpace14** [comment]
I just pushed a commit with the latest version which I think you can merge to the main if you feel it is good. 

I changed the text box sizing units - I'm not sure they are perfect but perhaps I bit better. 

I also added the cash in, play and discard buttons. 

Lastly - I added the function where if you click on each card it enlarges and centers in the screen. And if you click on the card again then it returns to its original position. 

Let me know what you think.

**Comment by smileydts** [comment]
It looks ok aside from that I'm still getting the sizing issue with the
text boxes that I had yesterday.  As far as clicking on the card goes, what
do you think about when you click on a card instead of moving to the center
of the screen, it just gets bumped up a little bit?  Or becomes
highlighted? I think I prefer it when elements don't change position too
much when they get clicked.

I resolved the merge conflicts.  I'll approve the PR in case you want to
merge and work on integrating the APIs, and come back to the visuals later.

**Comment by smileydts** [comment]
Oh yeah our PRs don't need approvals.
